# Generated by Django 3.0 on 2020-03-22 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200322_0126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='item',
            new_name='item_main',
        ),
    ]
